version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.16.1
    restart: unless-stopped
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      discovery.type: single-node
    volumes:
      - ./elk/configs/elasticsearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch-data:/usr/share/elasticsearch/data
    expose:
      - 9200
    networks:
      - elk_internal_network

  logstash:
    image: logstash:7.16.2
    restart: unless-stopped
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    volumes:
      - ./elk/configs/logstash/config.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./elk/configs/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./elk/configs/logstash/pipelines:/usr/share/logstash/config/pipelines:ro
    ports:
      - 5044:5044
    networks:
      - elk_internal_network
      - photobooth_external_network
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.16.1
    restart: unless-stopped
    environment:
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    volumes:
      - ./elk/configs/kibana/config.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - 5601:5601
    networks:
      - elk_internal_network
      - photobooth_external_network
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:

networks:
  elk_internal_network:
    driver: bridge
  photobooth_external_network:
    external: true
