version: '3'

services:
  app:
    build: ./app
    restart: unless-stopped
    environment:
      APP_PORT: ${APP_PORT}
      JDBC_DATABASE_URL: ${JDBC_DATABASE_URL}
      JDBC_DATABASE_USERNAME: ${JDBC_DATABASE_USERNAME}
      JDBC_DATABASE_PASSWORD: ${JDBC_DATABASE_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
#      CONSOLE_LOGS_IN_JSON: ${CONSOLE_LOGS_IN_JSON}  # [Optional]
#      EMAIL_ADDRESS: ${EMAIL_ADDRESS}                # [Optional]
#      EMAIL_PASSWORD: ${EMAIL_PASSWORD}              # [Optional]
#      LOGSTASH_HOST: ${LOGSTASH_HOST}                # [Optional]
#      LOGSTASH_PORT: ${LOGSTASH_PORT}                # [Optional]
    volumes:
      - ./logs:/logs
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - app_internal_network
      - external_network
    depends_on:
      - database

  database:
    image: postgres:14.0
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${JDBC_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${JDBC_DATABASE_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
        - postgres-data:/var/lib/postgresql/data
    networks:
      - app_internal_network

volumes:
  postgres-data:

networks:
  app_internal_network:
    driver: bridge
  external_network:
    driver: bridge
