version: '3'

services:
  photobooth:
    build: ./app
    restart: always
    environment:
      APP_PORT: ${APP_PORT}
      JDBC_DATABASE_URL: ${JDBC_DATABASE_URL}
      JDBC_DATABASE_USERNAME: ${JDBC_DATABASE_USERNAME}
      JDBC_DATABASE_PASSWORD: ${JDBC_DATABASE_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
#      EMAIL_ADDRESS: ${EMAIL_ADDRESS}    # [Optional]
#      EMAIL_PASSWORD: ${EMAIL_PASSWORD}  # [Optional]
#      LOGSTASH_HOST: ${LOGSTASH_HOST}    # [Optional]
#      LOGSTASH_PORT: ${LOGSTASH_PORT}    # [Optional]
    volumes:
      - ./logs:/logs
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - internal_network
      - elk_external_network
    depends_on:
      - database

  database:
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_USER: ${JDBC_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${JDBC_DATABASE_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
        - postgres-data:/var/lib/postgresql/data
    networks:
      - internal_network

volumes:
  postgres-data:

networks:
  internal_network:
    driver: bridge
  elk_external_network:
    external: true
