version: '3'

services:
  nginx:
    image: nginx:1.24
    restart: unless-stopped
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
    environment:
      PROXY_PASS_APP: ${PROXY_PASS_APP}
      PROXY_PASS_KIBANA: ${PROXY_PASS_KIBANA}
      PROXY_PASS_DOZZLE: ${PROXY_PASS_DOZZLE}
    ports:
      - 443:443
      - 5600:5600
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.template
      - ./nginx/ssl:/ssl/
    networks:
      - photobooth_external_network

networks:
  photobooth_external_network:
    external: true
