version: '3'

services:
  photobooth:
    build: ./app
    restart: always
    environment:
      APP_PORT: ${APP_PORT}
      JDBC_DATABASE_URL: ${JDBC_DATABASE_URL}
      JDBC_DATABASE_USERNAME: ${JDBC_DATABASE_USERNAME}
      JDBC_DATABASE_PASSWORD: ${JDBC_DATABASE_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      EMAIL_ADDRESS: ${EMAIL_ADDRESS}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
#    volumes:
#      - ./data/app/logs:/data/app/logs
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - internal_network
      - elk_external_network
    depends_on:
      - database

  database:
    image: postgres:14.0
    restart: always
#    volumes:
#        - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${JDBC_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${JDBC_DATABASE_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - internal_network

#TODO: Move to data/postgres/data
#volumes:
#  pgdata:

networks:
  internal_network:
    driver: bridge
  elk_external_network:
    external: true
