server:
  port: ${PORT}

management: # http://localhost:8080/actuator
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  h2: # http://localhost:8080/h2-console
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    show-sql: false
    database-platform: postgres
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    ru.drsanches.photobooth: INFO
#    org.springframework.transaction.interceptor: TRACE # For debug