spring.profiles.active: dev

log4j2.Script.enableLanguages: groovy

application:
  image:
    max-bytes: 300000 # 300kB
    thumbnail-size: 60 # width and height in pixels
  pagination:
    default-page-size: 20
    max-page-size: 100

management: # http://localhost:8080/actuator
  endpoints.web.exposure.include: "*"
  health.mail.enabled: false # enable for mail healthcheck

spring:
  mvc.static-path-pattern: /ui/**
  h2: # http://localhost:8080/h2-console
    console:
      enabled: true
      settings.web-allow-others: true
