server.port: ${APP_PORT}
log4j2.Script.enableLanguages: groovy

application:
  address: ${APPLICATION_ADDRESS} # With protocol and port. For push images and email confirms
  image:
    max-bytes: 300000 # 300kB
    thumbnail-size: 60 # width and height in pixels
  admin:
    username: admin
    password: ${ADMIN_PASSWORD}
  pagination:
    default-page-size: 20
    max-page-size: 100
  2fa:
    actions: ${2FA_ACTIONS:}
  notifications:
    email:
      enabled: true # must be true if application.notifications.2fa-enabled
      2fa-enabled: true # must be true if applications.2fa.actions is not empty
      info-enabled: false
    push:
      enabled: true
      firebase-credentials-path: firebase/firebase-service-account.json
  scheduler:
    expired-token-clean-task:
      enabled: true
      cron: 0 0 1 * * * # at 1 AM every day
    expired-confirmation-clean-task:
      enabled: true
      cron: 0 0 3 * * * # at 3 AM every day
    expired-fcm-token-clean-task:
      enabled: true
      cron: 0 0 5 * * * # at 5 AM every day

management: # http://localhost:8080/actuator
  endpoints.web.exposure.include: "*"
  health.mail.enabled: false # enable for mail healthcheck

spring:
  mvc.static-path-pattern: /ui/**
  h2: # http://localhost:8080/h2-console
    console:
      enabled: true
      settings.web-allow-others: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    database-platform: postgres
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  # Required if application.notifications.email.enabled
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.smtp.starttls.enable: true
