server:
  port: ${APP_PORT}

application:
  image:
    max-bytes: 300000 # 300kB
    thumbnail-size: 60 # width and height in pixels
  admin:
    username: admin
    password: ${ADMIN_PASSWORD}
  pagination:
    default-page-size: 20
    max-page-size: 100
  email-notifications:
    2FA-enabled: false
    email-sending-enabled: false # must be true if 2FA-enabled
  scheduler:
    expired-token-clean-task:
      enabled: true
      cron: 0 0 1 * * * # at 1 AM every day
    expired-confirmation-clean-task:
      enabled: true
      cron: 0 0 3 * * * # at 3 AM every day

management: # http://localhost:8080/actuator
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  mvc:
    static-path-pattern: /ui/**
  h2: # http://localhost:8080/h2-console
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    database-platform: postgres
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Required if application.email-sending-enabled
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.smtp.starttls.enable: true
