server.port: 8080

application:
  address: http://localhost:8080
  admin:
    username: admin
    password: admin
  2fa:
    actions:
  notifications:
    email:
      enabled: false
      2fa-enabled: false
      info-enabled: false
    push:
      enabled: false
  scheduler:
    expired-token-cleanup-task:
      enabled: false
    expired-confirmation-cleanup-task:
      enabled: false
    expired-fcm-token-cleanup-task:
      enabled: false

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect #TODO
