server.name: kibana
server.host: 0.0.0.0
monitoring.ui.container.elasticsearch.enabled: true

elasticsearch.hosts: [ "http://elasticsearch:9200" ]
elasticsearch.username: ${ELASTIC_USERNAME}
elasticsearch.password: ${ELASTIC_PASSWORD}
