package com.drsanches.photobooth.app.notifier.service.notifier;

public enum Action {

    REGISTRATION_STARTED,
    REGISTRATION_COMPLETED,
    USERNAME_CHANGE_STARTED,
    USERNAME_CHANGE_COMPLETED,
    PASSWORD_CHANGE_STARTED,
    PASSWORD_CHANGE_COMPLETED,
    EMAIL_CHANGE_STARTED,
    EMAIL_CHANGE_COMPLETED,
    DISABLE_STARTED,
    DISABLE_COMPLETED,
    IMAGE_SENT,
    ACCOUNT_LINKED,
    ACCOUNT_UNLINKED
}
